Smooth Ultraviolet Turkey

High

# permit2.permit() call is not handled as per advised of OpenZeppelin

### Summary

As per `OpenZeppelin` the `permit()` call will revert if the signature has been used before. It doesn't check if the destination has sufficient approval or not. So it is advised to wrap the `permit()` call in a try catch block and let the transaction revert in `transfer()` if there is insufficient allowance.

### Root Cause

1. https://github.com/sherlock-audit/2024-11-oku/blob/main/oku-custom-order-types/contracts/automatedTrigger/Bracket.sol#L328
2. https://github.com/sherlock-audit/2024-11-oku/blob/main/oku-custom-order-types/contracts/automatedTrigger/OracleLess.sol#L272
3. https://github.com/sherlock-audit/2024-11-oku/blob/main/oku-custom-order-types/contracts/automatedTrigger/StopLimit.sol#L391

### Internal pre-conditions

_No response_

### External pre-conditions

_No response_

### Attack Path

_No response_

### Impact

https://docs.openzeppelin.com/contracts/4.x/api/token/erc20#security_considerations

### PoC

_No response_

### Mitigation

It is recommended to handle the failure in the execution of `permit` as advised by [OpenZeppelin](https://docs.openzeppelin.com/contracts/4.x/api/token/erc20#security_considerations):
```solidity
function doThingWithPermit(..., uint256 value, uint256 deadline, uint8 v, bytes32 r, bytes32 s) public {
    try token.permit(msg.sender, address(this), value, deadline, v, r, s) {} catch {}
    doThing(..., value);
}

function doThing(..., uint256 value) public {
    token.safeTransferFrom(msg.sender, address(this), value);
    ...
}
```
